### ISSUE TITLE
Simple Deployment Guide Issues/Suggestions

### ISSUE THREAD

**Issue by OmisNomis** [reactioncommerce/proxy-traefik#1]
I went through your [Simple Deployment Guide](https://github.com/reactioncommerce/proxy-traefik/blob/master/docs/SimpleDeploymentGuide.md) and made a few notes on how it could be improved...

- Requirements say “A Linux host with at least 2GB of RAM” but the first section states “create a new droplet using the Ubuntu 18.4 image with at least 1GB of RAM “.

- Need to run `apt-get update` before `apt get build-essentials`

- `make` has to be run as `sudo` otherwise docker connection fails (permission error), which then creates a whole heap of other issues. It's best to ensure docker permissions are set first - `sudo usermod -a -G docker $USER`

- “Further, substitute REPLACE_WITH_PATH_TO_TRAEFIK_FOLDER with the path to the traefik folder” - this variable doesn’t exist, instead I had to update the paths under volumes manually.

- `docker create network` should be `docker network create`

- `chmod 600 acme.json` needs to be run

- Docker-compose `traefik.frontend.rule` label must be set to proper domain otherwise it fails.

These were just quick notes I made while going through the process. Unfortunately, after getting through it, I then had a load of other errors (e.g. OAuth2 errors) and I had to abandon and go another direction. 

Hope this helps 👍

**Comment by willopez** [comment]
@OmisNomis thank you for your feedback, most of your changes have been integrated, thanks!
