### ISSUE TITLE
Add proxy-traefik note to reaction-docs

### ISSUE THREAD

**Issue by agustif** [reactioncommerce/proxy-traefik#3]
This repo was hard to find for me, and also saved my day when trying to deploy with docker.

It would be great it to be mentioned on the docs, maybe it is and I didn't find it so easily?

Also, I understand docker-compose is not perfect for production, but since I'm launching a new website and expect 0 visits first day, I might go with it.

I'm guessing next steps would be to separate properly a mongodb cluster with shrading, replica_set, and what not.

And maybe the same for the hydra_postgresql instance.

I'm guessing kubernetes would be a next good step if one wanted to keep all in cloud services but controlling more the subjacent architecture or so.

Thanks for all your work, loving the framework, and can't wait for v3.0.0

**Comment by willopez** [comment]
@agustif This repo has not been released officially yet, however, it will be soon and it will be mentioned in the Reaction docs. And by the way, this guide has been updated to work with Reaction V3

**Comment by agustif** [comment]
> @agustif This repo has not been released officially yet, however, it will be soon and it will be mentioned in the Reaction docs. And by the way, this guide has been updated to work with Reaction V3

That's great to hear, might give it a try again on v3! Keep up the great work

**Comment by willopez** [comment]
going to reopen to remind me to do this.
