### ISSUE TITLE
Upgrade to traefik v2

### ISSUE THREAD

**Issue by agustif** [reactioncommerce/proxy-traefik#4]
I've tried to use https://github.com/containous/traefik-migration-tool to upgrade both the acme.json and traefik.toml, acme works fine, but with TOML, since v2 is scraping the backends/frontends and going with middlewares and what not, needs to be manually rewritten I think.
traefik-migration-tool acme works fine, but

➜ traefik-migration-tool static
Redirect on entry point "http" must be converted manually. See https://docs.traefik.io/v2.0/middlewares/redirectscheme/
TLS on entry point "https" must be converted manually. See https://docs.traefik.io/v2.0/routing/routers/#tls
The domain (domain.com) defined in the Docker provider must be converted manually. See https://docs.traefik.io/v2.0/providers/docker/#defaultrule
The entry point (dashboard) defined in API must be converted manually. See https://docs.traefik.io/v2.0/operations/api/
The entry point (https) defined in the ACME configuration must be converted manually. See https://docs.traefik.io/v2.0/routing/routers/#certresolver

**Comment by willopez** [comment]
Thanks for the suggestion @agustif, I'll be upgrading this guide to use Traefik V2.

**Comment by agustif** [comment]
hey no problem @willopez, thanks for fixing it =)

**Comment by willopez** [comment]
@agustif The guide has been updated to used Traefik v2
