### ISSUE TITLE
Volumes path in docker-compose.yml

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/proxy-traefik#7]
Hi,

The reaction.yml script don't set the volumes path in docker-compose.yml according to {{create_user}} and {{proxy_dir}} 

     - /home/reaction/proxy/traefik/traefik.yml:/traefik.yml:ro
     - /home/reaction/proxy/traefik/acme.json:/acme.jso

**Comment by willopez** [comment]
fixed
